apps/report/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.ReportIndexView.as_view(), name='index'),
	url(r'^generate/$', views.GenerateReportView.as_view(), name='generate'),
	url(r'^download/$', views.DownloadReportView.as_view(), name='download'),
#	url(r'^add/$', views.EntryAddView.as_view(), name='add'),
#	url(r'^view/(?P<pk>[0-9]+)/$', views.EntryDetailView.as_view(), name='view'),
#	url(r'^edit/(?P<pk>[0-9]+)/$', views.EntryEditView.as_view(), name='edit'),
#	url(r'^delete/(?P<pk>[0-9]+)/$', views.EntryDeleteView.as_view(), name='delete'),
#	url(r'^(?P<result>.*)$', views.EntryIndexView.as_view(), name='index'),
]

main_site/urls.py
from django.conf.urls import include, url
from django.contrib import admin

handler404 = 'apps.core.views.error404'
handler500 = 'apps.core.views.error500'

urlpatterns = [
	url(r'^admin/', admin.site.urls, name='admin'),
	url(r'^account/', include('apps.account.urls', namespace='account')),
	url(r'^client/', include('apps.client.urls', namespace='client')),
	url(r'^project/', include('apps.project.urls', namespace='project')),
	url(r'^entry/', include('apps.entry.urls', namespace='entry')),
	url(r'^login/', include('apps.login.urls', namespace='login')),
	url(r'^task/', include('apps.task.urls', namespace='task')),
	url(r'^report/', include('apps.report.urls', namespace='report')),
	url(r'^', include('apps.core.urls', namespace='index')),
]

apps/entry/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.timezone import now
from django.utils.translation import ugettext_lazy as _

from apps.client.models import Client
from apps.project.models import Project
from apps.task.models import Task


class Entry(models.Model):
	"""
	Entry table to be used by the Chronos platform.
	TODO: Develop this table
	"""

	description = models.TextField('Description')
	starttime = models.DateTimeField('Start date / time', blank=True, null=True)
	endtime = models.DateTimeField('End date / time', blank=True, null=True)
	duration = models.IntegerField('Duration', blank=True, null=True)
	comments = models.TextField('Comments', blank=True, null=True)
	project = models.ForeignKey(Project, on_delete=models.SET_NULL, db_column='Project', blank=True, null=True)
	client = models.ForeignKey(Client, on_delete=models.SET_NULL, db_column='Client', blank=True, null=True)
	user = models.ForeignKey(User, on_delete=models.SET_NULL, db_column='User', blank=True, null=True)
	task = models.ForeignKey(Task, on_delete=models.SET_NULL, db_column='Task', blank=True, null=True)
	cost = models.DecimalField('Cost', blank=True, null=True, default=0, max_digits=8, decimal_places=2)
	created = models.DateTimeField('Created', default=now, blank=True, null=True)
	last_updated = models.DateTimeField('Last Updated', default=now, blank=True, null=True)

	class Meta:
		# Translators: This string is used to identify the Account table name
		verbose_name = _('Entry')

		# Translators: This string is used to identify the Account table name in plural form
		verbose_name_plural = _('Entries')

apps/report/models.py
import os

from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils.timezone import now
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User


class Report(models.Model):
	"""
	Report table to be used by the Chronos platform.
	TODO: Develop this table
	"""

	name = models.CharField('Name', max_length=255)
	type = models.CharField('Type', max_length=255, blank=True, null=True)
	user = models.ForeignKey(User, on_delete=models.SET_NULL, db_column='User', blank=True, null=True)
	file = models.FileField(upload_to='reports',blank=True, null=True)
	filetype = models.CharField('File type', max_length=255, blank=True, null=True)
	created = models.DateTimeField('Created', default=now, blank=True, null=True)

	class Meta:
		# Translators: This string is used to identify the Report table name
		verbose_name = _('Report')

		# Translators: This string is used to identify the Report table name in plural form
		verbose_name_plural = _('Reports')

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('view', kwargs={'pk': self.pk})


class ReportType(models.Model):
	"""
	Report type table to be used by the Chronos platform.
	TODO: Develop this table
	"""
	code = models.CharField('Code', max_length=255)
	name = models.CharField('Name', max_length=255)
	description = models.TextField('Comments', blank=True, null=True)
	filetype = models.CharField('File type', max_length=255, blank=True, null=True)
	created = models.DateTimeField('Created', default=now, blank=True, null=True)

	class Meta:
		# Translators: This string is used to identify the Report type table name
		verbose_name = _('Report type')

		# Translators: This string is used to identify the Report type table name in plural form
		verbose_name_plural = _('Report types')

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('view', kwargs={'pk': self.pk})

apps/report/views.py
import os
import time

from decimal import Decimal

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.core.files.storage import FileSystemStorage
from django.db.models import Q
from django.http import HttpResponse, JsonResponse
from django.utils.translation import ugettext_lazy as _
from django.views.generic import TemplateView
from django.views.generic.list import ListView
from reportlab.lib.colors import grey, white, black
from reportlab.lib.pagesizes import landscape, A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
from reportlab.platypus.tables import Table, TableStyle

from apps.client.models import Client
from apps.entry.models import Entry
from apps.project.models import Project
from apps.report.models import Report
from apps.report.models import ReportType
from apps.task.models import Task

"""
Report views that are used to view, request, download and generate the reports in Chronos Platform
"""


class ReportIndexView(LoginRequiredMixin, ListView):
	"""
	View that is used to view and request reports to the Chronos platform.
	TODO: Develop this view
	"""

	template_name = 'report/report_index.html'
	model = Report

	def get_context_data(self, **kwargs):
		context = super(ReportIndexView, self).get_context_data(**kwargs)
		context['page_title'] = _('Reports - CHRONOS')
		context['report_active'] = 'active open'
		context['report_viewall_active'] = 'active'
		context['report_types'] = ReportType.objects.all().order_by('name')
		context['users'] = User.objects.all().filter(is_active=True).order_by('username')
		context['clients'] = Client.objects.filter(is_visible=True).all().order_by('name')
		context['tasks'] = Task.objects.all().filter(is_visible=True).order_by('name')
		context['projects'] = Project.objects.all().filter(is_visible=True).order_by('name')

		return context


class GenerateReportView(LoginRequiredMixin, TemplateView):
	"""
	View that is used to generate the reports for the Chronos platform.
	TODO: Develop this view
	"""
	template_name = 'report/report_index.html'

	@staticmethod
	def advanced_filter(request):
		"""
		Auxiliary function for advanced filtering
		:param the form request that will be used to fetch the filters:
		:return: an SQL filter using Q objects
		"""
		# Dictionary with advanced filtering
		qdict = {'starttime': 'starttime__gte',
		         'endtime': 'endtime__lte',
		         'task': 'task',
		         'user': 'user',
		         'client': 'client',
		         'project': 'project',
		         }

		q_objs = [Q(**{qdict[k]: request.POST.get(k)}) for k in qdict.keys() if request.POST.get(k, None)]

		q_objs_visibility = [
			Q(task__is_visible=True) | Q(task__isnull=True),
			Q(project__is_visible=True) | Q(project__isnull=True),
			Q(client__is_visible=True) | Q(client__isnull=True),
		]

		q_objs = q_objs + q_objs_visibility

		return q_objs

	def report_entryreportperprojectpdf(self, report_type):
		"""
		Generates a report that groups entries by project. All entries with no defined project are grouped on the
		same page.
		:param report_type: the requested report type
		:return: JSON with the result
		"""

		# standard distance for report
		margin = 1.5

		# Create the PDF object
		timestamp = int(time.time())
		filename = report_type + str(timestamp)
		pdf_report = SimpleDocTemplate('reports/{0}.pdf'.format(filename), author="Chronos Platform",
		                               rightMargin=margin * cm, leftMargin=margin * cm, topMargin=margin * cm,
		                               bottomMargin=margin * cm, pagesize=landscape(A4))
		# Prepares the filters
		q_objs = self.advanced_filter(self.request)

		# Fetch all filtered entries
		entries = Entry.objects.select_related().filter(*q_objs)
		projects = Entry.objects.all().order_by('project').filter(*q_objs).values_list('project', flat=True).distinct()

		# Style element used by the report
		styles = getSampleStyleSheet()

		# Report elements list
		elements = []

		# Sets the Header
		elements.append(Paragraph(_('Chronos entries per project report'), styles['Heading1']))
		elements.append(Spacer(36, 20))
		elements.append(Paragraph(_('Report created using Chronos platform'), styles['Heading2']))
		elements.append(Paragraph(_('Generated on %s') % time.ctime(time.time()), styles['Normal']))
		elements.append(PageBreak())

		# Iterate the projects in order to group entries per project
		# TODO: Is there an easier way to do this? Or maybe more correct?
		for project in projects:

			# Sets the individual page header
			if project is None:
				elements.append(Paragraph(_('Entries with no project defined'), styles['Heading2']))
			else:
				name = Project.objects.get(id=project).name
				elements.append(Paragraph(_('Entries for project "{0}"').format(name), styles['Heading2']))
			elements.append(Spacer(36, 20))
			table_data = [['Description', 'Start time', 'End time', 'Duration (min.)', 'Cost(EUR)', 'Comments', 'Task',
			               'Project', 'Client', 'User']]

			# Variable used to calculate the total cost for the sheet.
			total_cost = Decimal.from_float(0.00)

			# Iterates per entry in order to find the entry that corresponds to the project. When found, the entry
			# is added to the table
			for entry in entries:

				task_name = project_name = client_name = username = ''

				# Special case for the entries that have no project assigned.
				if not entry.project and project is None:

					if entry.task:
						task_name = entry.task.name
					if entry.client:
						client_name = entry.client.name
					if entry.user:
						username = entry.user.username

					total_cost += entry.cost

					table_data.append([
						entry.description,
						entry.starttime,
						entry.endtime,
						entry.duration,
						entry.cost,
						entry.comments,
						task_name,
						project_name,
						client_name,
						username
					])
				# All other cases with project assigned.
				elif entry.project and entry.project.id == project:

					project_name = entry.project.name

					if entry.task:
						task_name = entry.task.name
					if entry.client:
						client_name = entry.client.name
					if entry.user:
						username = entry.user.username

					total_cost += entry.cost

					table_data.append([
						entry.description,
						entry.starttime,
						entry.endtime,
						entry.duration,
						entry.cost,
						entry.comments,
						task_name,
						project_name,
						client_name,
						username
					])

			# Generates the table with the set data
			table = Table(table_data)
			table.setStyle(TableStyle(
				[
					('BACKGROUND', (0, 0), (9, 0), grey),
					('TEXTCOLOR', (0, 0), (9, 0), white),
					('ALIGN', (0, 0), (-1, -1), 'CENTER'),
					('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
					('INNERGRID', (0, 0), (-1, -1), 0.25, black),
					('BOX', (0, 0), (-1, -1), 0.25, black),
				]
			))

			# Appends the table to the report
			elements.append(table)
			elements.append(Spacer(36, 20))
			elements.append(Paragraph(_('Total cost: %s EUR') % total_cost, styles['Heading2']))
			elements.append(PageBreak())

		# Builds the report
		pdf_report.build(elements)

		# Temporarily stores the report in filesystem in order to assign it to the database
		fs = FileSystemStorage("reports")
		with fs.open("{0}.pdf".format(filename)) as pdf_report:
			Report.objects.create(
				name="{0}.pdf".format(filename),
				type=report_type,
				file=pdf_report,
				filetype='pdf',
				user=self.request.user
			)
		os.remove("reports/{0}.pdf".format(filename))

		# Returns JSON stating that the report was generated. However, for now, the return string is not used.
		data = {
			'result': 'report_generated',
		}
		return JsonResponse(data)

	def report_entryreportpertaskpdf(self, report_type):
		"""
		Generates a report that groups entries by task. All entries with no defined task are grouped on the
		same page.
		:param report_type: the requested report type
		:return: JSON with the result
		"""

		# standard distance for report
		margin = 1.5

		# Create the PDF object
		timestamp = int(time.time())
		filename = report_type + str(timestamp)
		pdf_report = SimpleDocTemplate('reports/{0}.pdf'.format(filename), author="Chronos Platform",
		                               rightMargin=margin * cm, leftMargin=margin * cm, topMargin=margin * cm,
		                               bottomMargin=margin * cm, pagesize=landscape(A4))
		# Prepares the filters
		q_objs = self.advanced_filter(self.request)

		# Fetch all filtered entries
		entries = Entry.objects.select_related().filter(*q_objs)
		tasks = Entry.objects.all().order_by('task').filter(*q_objs).values_list('task', flat=True).distinct()

		# Style element used by the report
		styles = getSampleStyleSheet()

		# Report elements list
		elements = []

		# Sets the Header
		elements.append(Paragraph(_('Chronos entries per task report'), styles['Heading1']))
		elements.append(Spacer(36, 20))
		elements.append(Paragraph(_('Report created using Chronos platform'), styles['Heading2']))
		elements.append(Paragraph(_('Generated on %s') % time.ctime(time.time()), styles['Normal']))
		elements.append(PageBreak())

		# Iterate the tasks in order to group entries per task
		# TODO: Is there an easier way to do this? Or maybe more correct?
		for task in tasks:

			# Sets the individual page header
			if task is None:
				elements.append(Paragraph(_('Entries with no task defined'), styles['Heading2']))
			else:
				name = Task.objects.get(id=task).name
				elements.append(Paragraph(_('Entries for task "{0}"').format(name), styles['Heading2']))
			elements.append(Spacer(36, 20))
			table_data = [['Description', 'Start time', 'End time', 'Duration (min.)', 'Cost(EUR)', 'Comments', 'Task',
			               'Project', 'Client', 'User']]

			# Variable used to calculate the total cost for the sheet.
			total_cost = Decimal.from_float(0.00)

apps/report/templates/report/report_index.html
{% extends "core/base.html" %}
{% load i18n widget_tweaks %}

{% block content %}
<div class="breadcrumbs ace-save-state" id="breadcrumbs">
    <ul class="breadcrumb">
        <li>
            <i class="ace-icon fa fa-home home-icon"></i>
            <a href="{% url 'index:index' %}">{% trans "Home" %}</a>
        </li>
        <li class="active">{% trans "Reports" %}</li>
    </ul><!-- /.breadcrumb -->
</div>
<div class="page-content">
    <div class="page-header">
        <h1>
            {% trans "Reports" %}
        </h1>
    </div><!-- /.page-header -->
    {% if result %}
    <div class="row">
        <div class="col-xs-12">
            <div class="alert alert-success">
                <button type="button" class="close" data-dismiss="alert">
                    <i class="ace-icon fa fa-times"></i>
                </button>
                <i class="ace-icon fa fa-check"></i> {{ result }}
                <br>
            </div>
        </div>
    </div>
    {% endif %}
    <div class="row">
        <div class="col-xs-12">
            <!-- PAGE CONTENT BEGINS -->
            <div class="row">
                <div class="col-xs-12">
                    <div class="clearfix">
                        <div class="widget-box widget-color-blue">
                            <div class="widget-header widget-header-small">
                                <h4 class="widget-title"><i class="ace-icon fa fa-sliders light-green bigger-130"></i>&nbsp;{% trans "Please select the report details" %}</h4>
                            </div>
                            <div class="widget-body" id="search-widget-body">
                                <div class="widget-main">
                                    <form id="report_form" method='POST' class="form-group" role="form" action='{% url 'report:generate' %}'>
                                        {% csrf_token %}
                                        <fieldset>
                                            <div class="form-group">
                                                <div class="row">
                                                    <div class="col-xs-4">
                                                        <h4 class="blue smaller">
                                                            <i class="fa fa-file-text-o brown bigger-110"></i>&nbsp;{% trans "Report type" %}
                                                        </h4>
                                                        <div class="row">
                                                            <div class="col-xs-12">
                                                                <select class="chosen-select form-control" id="id_report_type" name="report_type">
                                                                    <option value="" selected="selected">{% trans "Please select a report type" %}</option>
                                                                    {% for report_type in report_types %}
                                                                    <option value="{{report_type.code}}">{{report_type.name}}</option>
                                                                    {% endfor %}
                                                                </select>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="col-xs-4">
                                                        <h4 class="blue smaller">
                                                            <i class="fa fa-calendar green bigger-110"></i>&nbsp;{% trans "Date range" %}
                                                        </h4>
                                                        <div class="row">
                                                            <div class="col-xs-12">
                                                                <div class="input-daterange input-group">
                                                                    <input type="text" class="form-control" id="id_start_date" name="starttime">
                                                                    <span class="input-group-addon">
                                                                        <i class="fa fa-exchange"></i>
                                                                    </span>
                                                                    <input type="text" class="form-control" id="id_end_date" name="endtime">
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="col-xs-4">
                                                        <h4 class="blue smaller">
                                                            <i class="fa fa-pencil-square-o blue bigger-110"></i>&nbsp;{% trans "Additional filters" %}
                                                        </h4>
                                                        <div class="row">
                                                            <div class="col-xs-6">
                                                                <select class="chosen-select form-control" id="id_task" name="task">
                                                                    <option value="" selected="selected">{% trans "Please select a task" %}</option>
                                                                    {% for task in tasks %}
                                                                    <option value="{{task.id}}">{{task.name}}</option>
                                                                    {% endfor %}
                                                                </select>
                                                            </div>
                                                            <div class="col-xs-6">
                                                               <select class="chosen-select form-control" id="id_user" name="user">
                                                                    <option value="" selected="selected">{% trans "Please select a user" %}</option>
                                                                    {% for user in users %}
                                                                    <option value="{{user.id}}">{{user.username}}</option>
                                                                    {% endfor %}
                                                                </select>
                                                            </div>
                                                        </div>
                                                        <div class="space-4"></div>
                                                        <div class="row">
                                                            <div class="col-xs-6">
                                                                <select class="chosen-select col-xs-10 col-sm-5" id="id_client" name="client">
                                                                    <option value="" selected="selected">{% trans "Please select a client" %}</option>
                                                                    {% for client in clients %}
                                                                    <option value="{{client.id}}">{{client.name}}</option>
                                                                    {% endfor %}
                                                                </select>
                                                            </div>
                                                            <div class="col-xs-6">
                                                                <select class="chosen-select form-control" id="id_project" name="project">
                                                                    <option value="" selected="selected">{% trans "Please select a project" %}</option>
                                                                    {% for project in projects %}
                                                                    <option value="{{project.id}}">{{project.name}}</option>
                                                                    {% endfor %}
                                                                </select>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </fieldset>
                                        <div class="form-actions left no-margin">
                                             <button id="generate_report" type="submit" class="btn btn-default btn-round btn-white">
                                                <i class="ace-icon fa fa-print green"></i>
                                                {% trans "Generate report" %}
                                            </button>
                                            <button id="reset_report" type="reset" class="btn btn-default btn-round btn-white">
                                                <i class="ace-icon fa fa-remove red2"></i>
                                                {% trans "Reset" %}
                                            </button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="space-10"></div>
            <div class="row">
                <div class="col-xs-12">
                    <div class="clearfix">
                        <div class="pull-right tableTools-container"></div>
                    </div>
                    <div class="table-header">
                        {% trans "Results for Report listing" %}
                    </div>

                    <!-- div.table-responsive -->

                    <!-- div.dataTables_borderWrap -->
                    <div>
                        <table id="report-table" class="table table-striped table-bordered table-hover">
                            <thead>
                            <tr>
                                <th class="center">
                                    <label class="pos-rel">
                                        <input type="checkbox" class="ace"/>
                                        <span class="lbl"></span>
                                    </label>
                                </th>
                                <th>{% trans "Name" %}</th>
                                <th>{% trans "Created by" %}</th>
                                <th class="hidden-480">{% trans "File type" %}</th>
                                <th>{% trans "Created at" %}</th>
                                <th>{% trans "File" %}</th>
                                <th></th>
                            </tr>
                            </thead>

                            <tbody id="report-table-body">

                            {% for report in object_list %}
                            <tr id="pk-{{report.id}}">
                                <td class="center">
                                    <label class="pos-rel">
                                        <input type="checkbox" class="ace"/>
                                        <span class="lbl"></span>
                                    </label>
                                </td>

                                <td>{{report.name}}</td>
                                <td>{{report.user.username}}</td>
                                <td class="hidden-480">{{report.filetype}}</td>
                                <td>{{report.created | date:'Y-m-d H:i'}}</td>
                                <td>
                                    {% if report.file %}
                                    <form method='POST' class="form-group" role="form" action='{% url 'report:download'%}'>
                                        {% csrf_token %}
                                        <input type="hidden" value="{{report.id}}" name="pk"/>
                                        <button type="submit" class="btn btn-info">
                                            <i class="ace-icon fa fa-download bigger-125"></i>&nbsp;Download
                                        </button>
                                    </form>
                                    {% else %}
                                    <p class="small"> (no file available) </p>
                                    {% endif %}
                                </td>
                            </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="space-10"></div>
            <!-- PAGE CONTENT ENDS -->
        </div><!-- /.col -->
    </div><!-- /.row -->
</div><!-- /.page-content -->
{% endblock %}

{% block bottom %}
{% include "report/report_index_bottom_js.html" %}
{% endblock %}