apps/project/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.ProjectIndexView.as_view(), name='index'),
	url(r'^add/$', views.ProjectAddView.as_view(), name='add'),
	url(r'^view/(?P<pk>[0-9]+)/$', views.ProjectDetailView.as_view(), name='view'),
	url(r'^edit/(?P<pk>[0-9]+)/$', views.ProjectEditView.as_view(), name='edit'),
	url(r'^delete/(?P<pk>[0-9]+)/$', views.ProjectDeleteView.as_view(), name='delete'),
	url(r'^(?P<result>.*)$', views.ProjectIndexView.as_view(), name='index'),
]

main_site/urls.py
from django.conf.urls import include, url
from django.contrib import admin

handler404 = 'apps.core.views.error404'
handler500 = 'apps.core.views.error500'

urlpatterns = [
	url(r'^admin/', admin.site.urls, name='admin'),
	url(r'^account/', include('apps.account.urls', namespace='account')),
	url(r'^client/', include('apps.client.urls', namespace='client')),
	url(r'^project/', include('apps.project.urls', namespace='project')),
	url(r'^entry/', include('apps.entry.urls', namespace='entry')),
	url(r'^login/', include('apps.login.urls', namespace='login')),
	url(r'^task/', include('apps.task.urls', namespace='task')),
	url(r'^report/', include('apps.report.urls', namespace='report')),
	url(r'^', include('apps.core.urls', namespace='index')),
]

apps/project/models.py
from django.db import models
from django.utils.timezone import now
from django.utils.translation import ugettext_lazy as _


class Project(models.Model):
	"""
	Project table to be used by the Chronos platform.
	TODO: Develop this table
	"""

	name = models.CharField('Name', max_length=255)
	description = models.TextField('Description', blank=True, null=True)
	comments = models.TextField('Comments', blank=True, null=True)
	created = models.DateTimeField('Created', default=now, blank=True, null=True)
	last_updated = models.DateTimeField('Last Updated', default=now, blank=True, null=True)
	is_visible = models.BooleanField('Is Visible')

	class Meta:
		# Translators: This string is used to identify the Client table name
		verbose_name = _('Project')

		# Translators: This string is used to identify the Client table name in plural form
		verbose_name_plural = _('Projects')

apps/project/forms.py
from django.forms import ModelForm

from apps.project.models import Project


class ProjectForm(ModelForm):
	"""
	Project form used to add or update a project in the Chronos platform.
	TODO: Develop this form
	"""

	class Meta:
		model = Project
		fields = ['name', 'description', 'comments', 'is_visible']

apps/project/views.py
from datetime import datetime
from math import floor

from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.utils.translation import ugettext_lazy as _
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView

from apps.project.forms import ProjectForm
from apps.project.models import Project

"""
Project views created to manage the project CRUD operation.
"""


class ProjectIndexView(LoginRequiredMixin, ListView):
	"""
	View that is used to show all the projects that exist in the Chronos platform.
	Receives optional parameters to show alert functions:
	@param result (optional) - Shows alert functions accordingly

		Project added - YWRkZWQ=
		Project edited - ZWRpdGVk
		Project deleted - ZGVsZXRlZA==

	TODO: Develop this view
	"""

	template_name = 'project/project_index.html'
	model = Project

	def get_alert_information(self):
		"""
		Function used to generate the alert string based on the return result by URL
		:return: String containing the result message
		"""
		if 'result' in self.kwargs:
			if self.kwargs['result'] == 'YWRkZWQ=':
				return _("A new project was added with success!")
			if self.kwargs['result'] == 'ZWRpdGVk':
				return _("The project information was edited with success!")
			if self.kwargs['result'] == 'ZGVsZXRlZA==':
				return _("The project information was deleted with success!")

	def get_context_data(self, **kwargs):
		context = super(ProjectIndexView, self).get_context_data(**kwargs)
		context['page_title'] = _('Project list - CHRONOS')
		context['project_active'] = 'active open'
		context['project_viewall_active'] = 'active'
		context['result'] = self.get_alert_information()

		return context


class ProjectDetailView(LoginRequiredMixin, DetailView):
	"""
	View that is used to show the project information that exists in the Chronos platform.
	TODO: Develop this view
	"""

	template_name = "project/project_base.html"
	model = Project

	def get_context_data(self, **kwargs):
		context = super(ProjectDetailView, self).get_context_data(**kwargs)
		context['page_title'] = _('Project detail - CHRONOS')
		context['project_active'] = 'active open'
		context['project_viewall_active'] = 'active'
		context['progress'] = self.get_profile_completion()

		return context

	def get_profile_completion(self):
		"""
		This function is used to calculate the total percentage of the project's profile completion.
		:return: the calculated percentage
		"""
		project = self.get_object()
		filled_fields = 0
		total_fields = len(project._meta.fields)

		for field in project._meta.fields:
			if getattr(project, field.name):
				filled_fields += 1

		progression = floor((filled_fields / total_fields) * 100)

		return progression


class ProjectAddView(LoginRequiredMixin, CreateView):
	"""
	View that is used to add a new project in the Chronos platform.
	TODO: Develop this view
	"""

	model = Project
	form_class = ProjectForm
	template_name = 'project/project_form.html'

	def get_context_data(self, **kwargs):
		context = super(ProjectAddView, self).get_context_data(**kwargs)
		context['page_title'] = _('Add new project - CHRONOS')
		context['title'] = _('Add a new project')
		context['project_active'] = 'active open'
		context['project_add_active'] = 'active'
		context['project_list'] = self.get_queryset()
		context['is_new_project'] = True

		return context

	def form_valid(self, form):
		return super(ProjectAddView, self).form_valid(form)

	def get_success_url(self):
		return reverse_lazy('project:index', kwargs={'result': 'YWRkZWQ='})


class ProjectEditView(LoginRequiredMixin, UpdateView):
	"""
	View that is used to edit a project in the Chronos platform.
	TODO: Develop this view
	"""

	model = Project
	form_class = ProjectForm
	template_name = 'project/project_form.html'

	def get_context_data(self, **kwargs):
		context = super(ProjectEditView, self).get_context_data(**kwargs)
		context['page_title'] = _('Edit project - CHRONOS')
		context['title'] = _('Edit project')
		context['project_active'] = 'active open'
		context['project_viewall_active'] = 'active'
		context['is_new_project'] = False

		return context

	def form_valid(self, form):
		form.instance.last_updated = datetime.now()
		return super(ProjectEditView, self).form_valid(form)

	def get_success_url(self):
		return reverse_lazy('project:index', kwargs={'result': 'ZWRpdGVk'})


class ProjectDeleteView(LoginRequiredMixin, DeleteView):
	"""
	View that is used to delete a project in the Chronos platform. Accessed via AJAX call
	TODO: Develop this view
	"""
	model = Project
	template_name = 'project/project_delete_modal.html'

	def dispatch(self, *args, **kwargs):

		id = self.get_object().id

		response = super(ProjectDeleteView, self).dispatch(*args, **kwargs)
		if self.request.is_ajax():
			response_data = {"result": "ok", "id": id}
			return JsonResponse(response_data)
		else:
			# POST request (not ajax) will do a redirect to success_url
			return response

	def get_success_url(self):
		return reverse_lazy('project:index', kwargs={'result': 'ZGVsZXRlZA=='})

apps/project/templates/project/project.html
{% extends "core/base.html" %}
{% load i18n %}

{% block content %}
    <div class="breadcrumbs ace-save-state" id="breadcrumbs">
		<ul class="breadcrumb">
			<li>
				<i class="ace-icon fa fa-home home-icon"></i>
				<a href="{% url "index:index" %}">{% trans "Home" %}</a>
			</li>
			<li class="active">Clients</li>
		</ul><!-- /.breadcrumb -->
	</div>
   <div class="page-content">
		<div class="page-header">
			<h1>
				{% trans "Project list" %}
			</h1>
		</div><!-- /.page-header -->
		<div class="row">
			<div class="col-xs-12">
				<!-- PAGE CONTENT BEGINS -->
				<div class="row">
					<div class="col-xs-12">
						<div class="clearfix">
							<div class="pull-right tableTools-container"></div>
						</div>
						<div class="table-header">
							{% trans "Results for Project listing" %}
						</div>

						<!-- div.table-responsive -->

						<!-- div.dataTables_borderWrap -->
						<div>
							<table id="dynamic-table" class="table table-striped table-bordered table-hover">
								<thead>
									<tr>
										<th class="center">
											<label class="pos-rel">
												<input type="checkbox" class="ace" />
												<span class="lbl"></span>
											</label>
										</th>
										<th>{% trans "Name" %}</th>
										<th></th>
									</tr>
								</thead>

								<tbody>

									{% for project in project_list %}
										<tr>
											<td class="center">
												<label class="pos-rel">
													<input type="checkbox" class="ace" />
													<span class="lbl"></span>
												</label>
											</td>
											<td><a href="#">{{project.name}}</a></td>
											<td>
												<div class="hidden-sm hidden-xs action-buttons">
													<a class="blue" href="#">
														<i class="ace-icon fa fa-eye bigger-130"></i>
													</a>

													<a class="green" href="#">
														<i class="ace-icon fa fa-pencil bigger-130"></i>
													</a>

													<a class="red" href="#">
														<i class="ace-icon fa fa-trash-o bigger-130"></i>
													</a>
												</div>

												<div class="hidden-md hidden-lg">
													<div class="inline pos-rel">
														<button class="btn btn-minier btn-yellow dropdown-toggle" data-toggle="dropdown" data-position="auto">
															<i class="ace-icon fa fa-caret-down icon-only bigger-120"></i>
														</button>

														<ul class="dropdown-menu dropdown-only-icon dropdown-yellow dropdown-menu-right dropdown-caret dropdown-close">
															<li>
																<a href="#" class="tooltip-info" data-rel="tooltip" title="View">
																	<span class="blue">
																		<i class="ace-icon fa fa-eye bigger-120"></i>
																	</span>
																</a>
															</li>

															<li>
																<a href="#" class="tooltip-success" data-rel="tooltip" title="Edit">
																	<span class="green">
																		<i class="ace-icon fa fa-pencil-square-o bigger-120"></i>
																	</span>
																</a>
															</li>

															<li>
																<a href="#" class="tooltip-error" data-rel="tooltip" title="Delete">
																	<span class="red">
																		<i class="ace-icon fa fa-trash-o bigger-120"></i>
																	</span>
																</a>
															</li>
														</ul>
													</div>
												</div>
											</td>
										</tr>
									{% endfor %}
								</tbody>
							</table>
						</div>
					</div>
				</div>
				<!-- PAGE CONTENT ENDS -->
			</div><!-- /.col -->
		</div><!-- /.row -->
	</div><!-- /.page-content -->
{% endblock %}

{% block bottom %}
	{% include "client/client_bottom_js.html" %}
{% endblock %}

apps/project/templates/project/project_base.html
{% extends "core/base.html" %}
{% load i18n widget_tweaks %}

{% block content %}
<div class="breadcrumbs ace-save-state" id="breadcrumbs">
    <ul class="breadcrumb">
        <li>
            <i class="ace-icon fa fa-home home-icon"></i>
            <a href="{% url 'index:index' %}">{% trans "Home" %}</a>
        </li>
        <li>
            <a href="{% url 'project:index' %}">{% trans "Projects" %}</a>
        </li>
        <li class="active">{% trans "View detail" %}</li>
    </ul><!-- /.breadcrumb -->
</div>
<div class="page-content">
    <div class="page-header">
        <h1>
            {% trans "View detailed information for project " %} {{ object.name }}
        </h1>
    </div><!-- /.page-header -->
    <div class="row">
        <div class="col-xs-12">
            <!-- PAGE CONTENT BEGINS -->
            <div class="">
                <div class="tabbable">
                    <ul class="nav nav-tabs" id="projectTabs">
                        <li class="active">
                            <a data-toggle="tab" href="#basic" aria-expanded="true">
                                <i class="green ace-icon fa fa-info bigger-120"></i>
                                {% trans "Basic details" %}
                            </a>
                        </li>

                        <li class="">
                            <a data-toggle="tab" href="#additional" aria-expanded="false">
                                <i class="blue ace-icon fa fa-list-alt bigger-120"></i>
                                {% trans "Additional details" %}
                            </a>
                        </li>

                    </ul>

                    <div class="tab-content">
                        <div id="basic" class="tab-pane fade active in">
                            <div class="profile-user-info">
                                <div class="profile-info-row">
                                    <div class="profile-info-name">{% trans "Name" %}</div>
                                    <div class="profile-info-value">{{ object.name }}</div>
                                </div>
                                <div class="profile-info-row">
                                    <div class="profile-info-name">{% trans "Is visible?" %}</div>
                                    <div class="profile-info-value">{{ object.is_visible }}</div>
                                </div>
                            </div>
                        </div>

                        <div id="additional" class="tab-pane fade">
                            <div class="profile-user-infod">
                                <div class="profile-info-row">
                                    <div class="profile-info-name">{% trans "Description" %}</div>
                                    <div class="profile-info-value">{{ object.description }}</div>
                                </div>
                                <div class="profile-info-row">
                                    <div class="profile-info-name">{% trans "Comments" %}</div>
                                    <div class="profile-info-value">{{ object.comments }}</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="">
                <div class="well well-lg">
                    <div class="inline middle blue bigger-110"> Project profile completion:</div>
                    <br/><br/>
                    <div style="width:100%;" data-percent="{{ progress }}%"
                         class="inline middle no-margin progress progress-striped pos-rel">
                        <div class="progress-bar progress-bar-success" style="width:{{ progress }}%"></div>
                    </div>
                </div>
            </div>
            <div class="clearfix form-actions">
                <div class="col-md-offset-3 col-md-9">
                    <a class="btn btn-info" href="{% url 'project:edit' pk=object.id %}">
                        <i class="ace-icon fa fa-pencil bigger-110"></i>
                        {% trans "Edit" %}
                    </a>
                    &nbsp; &nbsp; &nbsp;
                    <a class="btn btn-danger" href="{% url 'project:index' %}">
                        <i class="ace-icon fa fa-times bigger-110"></i>
                        {% trans "Close" %}
                    </a>
                </div>
            </div>
            <!-- PAGE CONTENT ENDS -->
        </div><!-- /.col -->
    </div><!-- /.row -->
</div><!-- /.page-content -->
{% endblock %}

{% block bottom %}
{% include "project/project_form_bottom_js.html" %}
{% endblock %}

apps/project/templates/project/project_delete_modal.html
{% load i18n %}
<div class="modal-dialog">
    <div class="modal-content">
        <form action="" method='POST'>
            {% csrf_token %}
            <div class="modal-header">
                <h4 class="modal-title">{% trans "Delete project" %}</h4>
            </div>
            <div class="modal-body">
                <p>
                    {% trans "Are you sure you would like to delete this project? You will not be able to undo this
                    operation!" %}
                </p>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary">{% trans "Delete" %}</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">{% trans "Cancel" %}</button>
            </div>
        </form>
    </div
</div>

apps/project/templates/project/project_form.html
{% extends "core/base.html" %}
{% load i18n widget_tweaks %}

{% block content %}
<div class="breadcrumbs ace-save-state" id="breadcrumbs">
    <ul class="breadcrumb">
        <li>
            <i class="ace-icon fa fa-home home-icon"></i>
            <a href="{% url 'index:index' %}">{% trans "Home" %}</a>
        </li>
        <li>
            <a href="{% url 'project:index' %}">{% trans "Projects" %}</a>
        </li>
        <li class="active">{{ title }}</li>
    </ul><!-- /.breadcrumb -->
</div>
<div class="page-content">
    <div class="page-header">
        <h1>
            {{ title }}
        </h1>
    </div><!-- /.page-header -->
    <div class="row">
        <div class="col-xs-12">
            <!-- PAGE CONTENT BEGINS -->
            <form method='POST' class="form-horizontal" role="form" action=''>
                {% csrf_token %}
                {{ form.non_field_errors }}
                <div class="widget-box">
                    <div class="widget-header">
                        <h4 class="widget-title">{% trans "Basic details" %}</h4>

                        <div class="widget-toolbar">
                            <a href="#" data-action="collapse">
                                <i class="ace-icon fa fa-chevron-up"></i>
                            </a>
                        </div>
                    </div>
                    <div class="widget-body">
                        <div class="widget-main">
                            <div class="form-group">
                                <label class="col-sm-3 control-label no-padding-right"
                                       for='{{ form.name.id_for_label }}'>{% trans "Name" %} </label>
                                <div class="col-sm-9">
                                    {% trans "Project name" as project_name %}
                                    {% render_field form.name placeholder=project_name class="col-xs-10 col-sm-5" %}
                                    {{ form.name.errors }}
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label no-padding-right"
                                       for='{{ form.is_visible.id_for_label }}'>{% trans "Is visible" %} </label>
                                <div class="col-sm-9">
                                    <label>
                                        {% trans "Is visible?" as visibility %}
                                        {% render_field form.is_visible type="checkbox" class="ace ace-switch ace-switch-2" %}
                                        <span class="lbl"></span>
                                    </label>
                                    {{ form.is_visible.errors }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="widget-box">
                    <div class="widget-header">
                        <h4 class="widget-title">{% trans "Additional information" %}</h4>

                        <div class="widget-toolbar">
                            <a href="#" data-action="collapse">
                                <i class="ace-icon fa fa-chevron-up"></i>
                            </a>
                        </div>
                    </div>
                    <div class="widget-body">
                        <div class="widget-main">
                            <div class="form-group">
                                <label class="col-sm-3 control-label no-padding-right"
                                       for="{{ form.description.id_for_label }}">{% trans "Description" %} </label>
                                <div class="col-sm-9">
                                    {% trans "Enter your description here" as description %}
                                    {% render_field form.description placeholder=description class="form-control" %}
                                    {{ form.description.errors }}
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label no-padding-right"
                                       for="{{ form.comments.id_for_label }}">{% trans "Comments" %} </label>
                                <div class="col-sm-9">
                                    {% trans "Enter your comments here" as comments %}
                                    {% render_field form.comments placeholder=comments class="form-control" %}
                                    {{ form.comments.errors }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="clearfix form-actions">
                    <div class="col-md-offset-3 col-md-9">
                        <button class="btn btn-info" type="submit">
                            <i class="ace-icon fa fa-check bigger-110"></i>
                            {% if is_new_project %}
                            {% trans "Submit" %}
                            {% else %}
                            {% trans "Update" %}
                            {% endif %}
                        </button>
                        {% if is_new_project %}
                        &nbsp; &nbsp; &nbsp;
                        <button class="btn" type="reset">
                            <i class="ace-icon fa fa-undo bigger-110"></i>
                            {% trans "Reset" %}
                        </button>
                        {% endif %}
                        &nbsp; &nbsp; &nbsp;
                        <a class="btn btn-danger" href="{% url 'project:index' %}">
                            <i class="ace-icon fa fa-times bigger-110"></i>
                            {% trans "Cancel" %}
                        </a>
                    </div>
                </div>
            </form><!-- PAGE CONTENT ENDS -->
        </div><!-- /.col -->
    </div><!-- /.row -->
</div><!-- /.page-content -->
{% endblock %}

{% block bottom %}
{% include "project/project_form_bottom_js.html" %}
{% endblock %}

apps/project/templates/project/project_index.html
{% extends "core/base.html" %}
{% load i18n %}

{% block content %}
<div class="breadcrumbs ace-save-state" id="breadcrumbs">
    <ul class="breadcrumb">
        <li>
            <i class="ace-icon fa fa-home home-icon"></i>
            <a href="{% url 'index:index' %}">{% trans "Home" %}</a>
        </li>
        <li class="active">{% trans "Projects" %}</li>
    </ul><!-- /.breadcrumb -->
</div>
<div class="page-content">
    <div class="page-header">
        <h1>
            {% trans "Project list" %}
        </h1>
    </div><!-- /.page-header -->
    {% if result %}
    <div class="row">
        <div class="col-xs-12">
            <div class="alert alert-success">
                <button type="button" class="close" data-dismiss="alert">
                    <i class="ace-icon fa fa-times"></i>
                </button>
                <i class="ace-icon fa fa-check"></i> {{ result }}
                <br>
            </div>
        </div>
    </div>
    {% endif %}
    <div class="row">
        <div class="col-xs-12">
            <!-- PAGE CONTENT BEGINS -->
            <div class="row">
                <div class="col-xs-12">
                    <div class="clearfix">
                        <div class="pull-right tableTools-container"></div>
                    </div>
                    <div class="table-header">
                        {% trans "Results for Project listing" %}
                    </div>

                    <!-- div.table-responsive -->

                    <!-- div.dataTables_borderWrap -->
                    <div>
                        <table id="project-table" class="table table-striped table-bordered table-hover">
                            <thead>
                            <tr>
                                <th class="center">
                                    <label class="pos-rel">
                                        <input type="checkbox" class="ace"/>
                                        <span class="lbl"></span>
                                    </label>
                                </th>
                                <th>{% trans "Name" %}</th>
                                <th class="hidden-480">{% trans "Description" %}</th>
                                <th class="hidden-480">{% trans "Comments" %}</th>
                                <th>{% trans "Is Visible?" %}</th>
                                <th></th>
                            </tr>
                            </thead>

                            <tbody id="project-table-body">

                            {% for project in object_list %}
                            <tr id="pk-{{project.id}}">
                                <td class="center">
                                    <label class="pos-rel">
                                        <input type="checkbox" class="ace"/>
                                        <span class="lbl"></span>
                                    </label>
                                </td>

                                <td><a href="#">{{project.name}}</a></td>
                                <td class="hidden-480">{{project.description}}</td>
                                <td class="hidden-480">{{project.comments}}</td>
                                <td>{{project.is_visible}}</td>
                                <td>
                                    <div class="hidden-sm hidden-xs action-buttons">
                                        <a class="blue" href="{% url 'project:view' pk=project.id %}">
                                            <i class="ace-icon fa fa-eye bigger-130"></i>
                                        </a>

                                        <a class="green" href="{% url 'project:edit' pk=project.id %}">
                                            <i class="ace-icon fa fa-pencil bigger-130"></i>
                                        </a>

                                        <a class="delete red" href="{% url 'project:delete' pk=project.id %}"
                                           title="Delete project information" data-tooltip>
                                            <i class="ace-icon fa fa-trash-o bigger-130"></i>
                                        </a>
                                    </div>
                                </td>
                            </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <!-- PAGE CONTENT ENDS -->
        </div><!-- /.col -->
    </div><!-- /.row -->
</div><!-- /.page-content -->
{% endblock %}

{% block bottom %}
{% include "project/project_index_bottom_js.html" %}
{% endblock %}