apps/core/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.CoreIndexView.as_view(), name='index'),
]

apps/login/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.LoginView.as_view(), name='index'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
]

apps/task/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.TaskIndexView.as_view(), name='index'),
	url(r'^add/$', views.TaskAddView.as_view(), name='add'),
	url(r'^view/(?P<pk>[0-9]+)/$', views.TaskDetailView.as_view(), name='view'),
	url(r'^edit/(?P<pk>[0-9]+)/$', views.TaskEditView.as_view(), name='edit'),
	url(r'^delete/(?P<pk>[0-9]+)/$', views.TaskDeleteView.as_view(), name='delete'),
	url(r'^(?P<result>.*)$', views.TaskIndexView.as_view(), name='index'),
]

main_site/urls.py
from django.conf.urls import include, url
from django.contrib import admin

handler404 = 'apps.core.views.error404'
handler500 = 'apps.core.views.error500'

urlpatterns = [
	url(r'^admin/', admin.site.urls, name='admin'),
	url(r'^account/', include('apps.account.urls', namespace='account')),
	url(r'^client/', include('apps.client.urls', namespace='client')),
	url(r'^project/', include('apps.project.urls', namespace='project')),
	url(r'^entry/', include('apps.entry.urls', namespace='entry')),
	url(r'^login/', include('apps.login.urls', namespace='login')),
	url(r'^task/', include('apps.task.urls', namespace='task')),
	url(r'^report/', include('apps.report.urls', namespace='report')),
	url(r'^', include('apps.core.urls', namespace='index')),
]

apps/core/models.py
# Create your models here.

apps/entry/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.timezone import now
from django.utils.translation import ugettext_lazy as _

from apps.client.models import Client
from apps.project.models import Project
from apps.task.models import Task


class Entry(models.Model):
	"""
	Entry table to be used by the Chronos platform.
	TODO: Develop this table
	"""

	description = models.TextField('Description')
	starttime = models.DateTimeField('Start date / time', blank=True, null=True)
	endtime = models.DateTimeField('End date / time', blank=True, null=True)
	duration = models.IntegerField('Duration', blank=True, null=True)
	comments = models.TextField('Comments', blank=True, null=True)
	project = models.ForeignKey(Project, on_delete=models.SET_NULL, db_column='Project', blank=True, null=True)
	client = models.ForeignKey(Client, on_delete=models.SET_NULL, db_column='Client', blank=True, null=True)
	user = models.ForeignKey(User, on_delete=models.SET_NULL, db_column='User', blank=True, null=True)
	task = models.ForeignKey(Task, on_delete=models.SET_NULL, db_column='Task', blank=True, null=True)
	cost = models.DecimalField('Cost', blank=True, null=True, default=0, max_digits=8, decimal_places=2)
	created = models.DateTimeField('Created', default=now, blank=True, null=True)
	last_updated = models.DateTimeField('Last Updated', default=now, blank=True, null=True)

	class Meta:
		# Translators: This string is used to identify the Account table name
		verbose_name = _('Entry')

		# Translators: This string is used to identify the Account table name in plural form
		verbose_name_plural = _('Entries')

apps/task/models.py
from django.db import models
from django.utils.timezone import now
from django.utils.translation import ugettext_lazy as _


class Task(models.Model):
	"""
	Task table to be used by the Chronos platform.
	TODO: Develop this table
	"""

	name = models.CharField('Name', max_length=255)
	description = models.TextField('Description', blank=True, null=True)
	comments = models.TextField('Comments', blank=True, null=True)
	price = models.DecimalField('Price', blank=True, null=True, default=0, max_digits=8, decimal_places=2)
	parenttask = models.ForeignKey('self', on_delete=models.SET_NULL, db_column='Parent task', blank=True, null=True)
	created = models.DateTimeField('Created', default=now, blank=True, null=True)
	last_updated = models.DateTimeField('Last Updated', default=now, blank=True, null=True)
	is_visible = models.BooleanField('Is Visible')

	class Meta:
		# Translators: This string is used to identify the Client table name
		verbose_name = _('Task')

		# Translators: This string is used to identify the Client table name in plural form
		verbose_name_plural = _('Tasks')

apps/core/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.translation import ugettext_lazy as _
from django.views.generic import TemplateView
from django.db.models import Count, Q

from apps.entry.models import Entry
from apps.client.models import Client
from apps.project.models import Project
from apps.task.models import Task

"""
Main views for the Chronos platform
"""


class CoreIndexView(LoginRequiredMixin, TemplateView):
    """
    View that is used to show the Chronos dashboard
    TODO: Develop this view
    """

    template_name = 'core/dashboard.html'

    def get_context_data(self, **kwargs):
        context = super(CoreIndexView, self).get_context_data(**kwargs)
        context['page_title'] = _('Dashboard - CHRONOS')
        context['dashboard'] = 'active'
        context['totals'] = self.get_totals_user()
        context['last_entry'] = self.get_last_entry()
        context['latest'] = self.get_latest()
        context['clients'] = Client.objects.all().filter(is_visible=True)
        context['tasks'] = Task.objects.all().filter(is_visible=True)
        context['projects'] = Project.objects.all().filter(is_visible=True)

        return context

    @staticmethod
    def entry_filter(request=None):
        """
        Function used to fill out predefined filter fields for the entries, especially related with
        the objects visibility.
        :param request: the form request (optional) in order to fetch the current user as filter
        :return: a list of Q objects for filter
        """
        q_objs = [
            Q(task__is_visible=True) | Q(task__isnull=True),
            Q(project__is_visible=True) | Q(project__isnull=True),
            Q(client__is_visible=True) | Q(client__isnull=True),
        ]

        if request:
            q_objs.append(Q(user=request.user))

        return q_objs

    def get_latest(self):
        """
        Function that fetches and returns the latest 10 tasks, clients and project objects
        created in the Chronos platform
        :return: a list of Querysets
        """
        latest = {}

        try:
            latest['tasks'] = Task.objects.order_by('id').filter(is_visible=True)[:10]
        except IndexError:
            latest['tasks'] = None

        try:
            latest['clients'] = Client.objects.order_by('id').filter(is_visible=True)[:10]
        except IndexError:
            latest['clients'] = None

        try:
            latest['projects'] = Project.objects.order_by('id').filter(is_visible=True)[:10]
        except IndexError:
            latest['projects'] = None

        return latest

    def get_last_entry(self):
        """
        Function that fetches and returns the latest entry submitted by the current user into the
        Chronos platform
        :return: Queryset object
        """
        try:
            return Entry.objects.filter(*self.entry_filter(self.request)).order_by('-starttime')[0]
        except IndexError:
            return None

    def get_totals_user(self):
        """
        Function that calculates and returns the dashboard's current defined KPI for the Chronos platform
        :return: a list of several KPI / gran totals
        """
        totals = {}

        # calculates the total user entries in the platform. Returns 0 if user has no entries.
        try:
            totals['user_entries'] = Entry.objects.filter(*self.entry_filter(self.request)).count()
        except Entry.DoesNotExist:
            totals['user_entries'] = 0

        # Calculates the total user clients with whom the user has worked with in the platform.
        # Returns 0 if user has no entries.
        try:
            totals['user_clients'] = Entry.objects.filter(*self.entry_filter(self.request)).filter(client__isnull=False)\
                .values('client').distinct().count()
        except Entry.DoesNotExist:
            totals['user_clients'] = 0

        # Calculates the total user projects where the user has worked in the platform.
        # Returns 0 if user has no entries.
        try:
            totals['user_projects'] = Entry.objects.filter(*self.entry_filter(self.request)).filter(project__isnull=False)\
                .values('project').distinct().count()
        except Entry.DoesNotExist:
            totals['user_projects'] = 0

        # Calculates the total user tasks that the user has performed in the platform.
        # Returns 0 if user has no entries.
        try:
            totals['user_tasks'] = Entry.objects.filter(*self.entry_filter(self.request)).filter(task__isnull=False)\
                .values('task').distinct().count()
        except Entry.DoesNotExist:
            totals['user_tasks'] = 0

        # Calculates the total entries, clients, projects and tasks existing in the platform that have
        # their visibility active
        totals['entries'] = Entry.objects.all().filter(*self.entry_filter()).count()
        totals['clients'] = Client.objects.all().filter(is_visible=True).count()
        totals['projects'] = Project.objects.all().filter(is_visible=True).count()
        totals['tasks'] = Task.objects.all().filter(is_visible=True).count()

        # Taking into account the user_entries vs the total entries KPIs, calculates the total percentage
        # Returns 0 if user has no entries.
        try:
            totals['user_entries_percent'] = int(round((totals['user_entries'] / totals['entries']) * 100))
        except ZeroDivisionError:
            totals['user_entries_percent'] = 0

        # Taking into account the user_clients vs the total clients KPIs, calculates the total percentage
        # Returns 0 if user has no entries.
        try:
            totals['user_clients_percent'] = int(round((totals['user_clients'] / totals['clients']) * 100))
        except ZeroDivisionError:
            totals['user_clients_percent'] = 0

        # Taking into account the user_projects vs the total projects KPIs, calculates the total percentage
        # Returns 0 if user has no entries.
        try:
            totals['user_projects_percent'] = int(round((totals['user_projects'] / totals['projects']) * 100))
        except ZeroDivisionError:
            totals['user_projects_percent'] = 0

        # Taking into account the user_tasks vs the total tasks KPIs, calculates the total percentage
        # Returns 0 if user has no entries.
        try:
            totals['user_tasks_percent'] = int(round((totals['user_tasks'] / totals['tasks']) * 100))
        except ZeroDivisionError:
            totals['user_tasks_percent'] = 0

        # Calculates and returns the total amount of user entries per client.
        totals['user_per_client_entries'] = Entry.objects.all().filter(*self.entry_filter(self.request)).filter(
            client__isnull=False).values('client__name').annotate(Count('client'))

        # Calculates and returns the total amount of user entries per task.
        totals['user_per_task_entries'] = Entry.objects.all().filter(*self.entry_filter(self.request)).filter(
            task__isnull=False).values('task__name').annotate(Count('task'))

        # Calculates and returns the total amount of user entries per project.
        totals['user_per_project_entries'] = Entry.objects.all().filter(*self.entry_filter(self.request)).filter(
            project__isnull=False).values('project__name').annotate(Count('project'))

        return totals


def error404(request):
    return render(request, 'errors/404.html')


def error500(request):
    return render(request, 'errors/500.html')

apps/core/templates/core/base.html
{% load i18n staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    <meta charset="utf-8"/>
    <title>{{ page_title }}</title>

    <meta name="description" content="overview &amp; stats"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0"/>

    {% block header %}
    {% include "core/header_styles.html" %}
    {% include "core/header_js.html" %}
    {% endblock %}
</head>
<body class="no-skin">
{% block navigation %}
{% include "core/nav_menu.html" %}
{% endblock %}
<div class="main-container ace-save-state" id="main-container">
    <script type="text/javascript">
        try {
            ace.settings.loadState('main-container')
        } catch (e) {
        }
    </script>
    {% block siderbar %}
    {% include "core/sidebar.html" %}
    {% endblock %}
    <div class="main-content">
        <div class="main-content-inner">
            {% block content %}
            {% endblock %}
        </div>
    </div><!-- /.main-content -->


    {% block footer %}
    {% include "core/footer.html" %}
    {% endblock %}
</div><!-- /.main-container -->
{% include "core/bottom_js.html" %}
{% block bottom %}
{% endblock %}
</body>
</html>

apps/core/templates/core/bottom_js.html
{% load staticfiles compress %}

{% compress js %}
<!-- ace settings handler -->
<script src='{% static "core/js/ace-extra.min.js" %}'></script>

<!-- HTML5shiv and Respond.js for IE8 to support HTML5 elements and media queries -->

<!--[if lte IE 8]>
<script src='{% static "core/js/html5shiv.min.js" %}'></script>
<script src='{% static "core/js/respond.min.js" %}'></script>
<![endif]-->

<!-- basic scripts -->

<!--[if !IE]> -->
<script src='{% static "core/js/jquery-2.1.4.min.js" %}'></script>

<!-- <![endif]-->

<!--[if IE]>
<script src='{% static "core/js/jquery-1.11.3.min.js" %}'></script>
<![endif]-->
<script type="text/javascript">
    if ('ontouchstart' in document.documentElement) document.write("<script src=\"{% static 'core/js/jquery.mobile.custom.min.js' %}\">" + "<" + "/script>")
</script>
<script src='{% static "core/js/bootstrap.min.js" %}'></script>
<script src='{% static "core/js/jquery-confirm.min.js" %}'></script>
{% endcompress %}

apps/core/templates/core/footer.html
{% load i18n %}

<div class="footer">
    <div class="footer-inner">
        <div class="footer-content">
			<span class="bigger-120">
				<span class="blue bolder"><i class="fa fa-clock-o"></i> Chronos</span> &copy; 2017
			</span>
            <span class="action-buttons">
				<a href="https://github.com/hgpestana/chronos">
					<i class="ace-icon fa fa-github red bigger-150"></i>
				</a>
			</span>
        </div>
    </div>
</div>

<a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse">
    <i class="ace-icon fa fa-angle-double-up icon-only bigger-110"></i>
</a>

apps/core/templates/core/header_js.html
{% load staticfiles compress %}

{% compress js %}
<!-- ace settings handler -->
<script src='{% static "core/js/ace-extra.min.js" %}'></script>

<!-- HTML5shiv and Respond.js for IE8 to support HTML5 elements and media queries -->

<!--[if lte IE 8]>
<script src='{% static "core/js/html5shiv.min.js" %}'></script>
<script src='{% static "core/js/respond.min.js" %}'></script>
<![endif]-->
{% endcompress %}

apps/core/templates/core/header_styles.html
{% load staticfiles compress %}

{% compress css %}

<!-- bootstrap & fontawesome -->
<link rel="stylesheet" href='{% static "core/css/bootstrap.min.css" %}'/>
<link rel="stylesheet" href='{% static "core/css/bootstrap-datepicker3.min.css" %}'/>
<link rel="stylesheet" href='{% static "core/font-awesome/4.5.0/css/font-awesome.min.css" %}'/>

<!-- Jquery Confirm -->
<link rel="stylesheet" href='{% static "core/css/jquery-confirm.min.css" %}'/>

<!-- Datetimepicker -->
<link rel="stylesheet" href='{% static "core/css/jquery.datetimepicker.min.css" %}'/>

<!-- Chosen plugin -->
<link rel="stylesheet" href='{% static "core/css/chosen.min.css" %}'/>

<!-- Summernote plugin -->
<link rel="stylesheet" href='{% static "core/css/summernote.css" %}'/>

<!-- Timecircles plugin -->
<link rel="stylesheet" href='{% static "core/css/timecircles.css" %}'/>

<!-- page specific styles -->
<link rel="stylesheet" href='{% static "core/css/custom.css" %}'/>

<!-- text fonts -->
<link rel="stylesheet" href='{% static "core/css/fonts.googleapis.com.css" %}'/>

<!-- ace styles -->
<link rel="stylesheet" href='{% static "core/css/ace.min.css" %}' class="ace-main-stylesheet" id="main-ace-style"/>

<!--[if lte IE 9]>
<link rel="stylesheet" href='{% static "core/css/ace-part2.min.css" %}' class="ace-main-stylesheet"/>
<![endif]-->
<link rel="stylesheet" href='{% static "core/css/ace-skins.min.css" %}'/>
<link rel="stylesheet" href='{% static "core/css/ace-rtl.min.css" %}'/>

<!--[if lte IE 9]>
<link rel="stylesheet" href='{% static "core/css/ace-ie.min.css" %}'/>
<![endif]-->

{% endcompress %}

apps/core/templates/core/nav_menu.html
{% load i18n %}

<div id="navbar" class="navbar navbar-default          ace-save-state">
    <div class="navbar-container ace-save-state" id="navbar-container">
        <button type="button" class="navbar-toggle menu-toggler pull-left" id="menu-toggler" data-target="#sidebar">
            <span class="sr-only">Toggle sidebar</span>

            <span class="icon-bar"></span>

            <span class="icon-bar"></span>

            <span class="icon-bar"></span>
        </button>

        <div class="navbar-header pull-left">
            <a href="{% url 'index:index' %}" class="navbar-brand">
                <small>
                    <i class="fa fa-clock-o"></i>
                    {% trans "CHRONOS" %}
                </small>
            </a>
        </div>

        <div class="navbar-buttons navbar-header pull-right" role="navigation">
            <ul class="nav ace-nav">

                <!--<li class="purple dropdown-modal">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <i class="ace-icon fa fa-bell icon-animated-bell"></i>
                        <span class="badge badge-important">8</span>
                    </a>

                    <ul class="dropdown-menu-right dropdown-navbar navbar-pink dropdown-menu dropdown-caret dropdown-close">
                        <li class="dropdown-header">
                            <i class="ace-icon fa fa-exclamation-triangle"></i>
                            8 Notifications
                        </li>

                        <li class="dropdown-content">
                            <ul class="dropdown-menu dropdown-navbar navbar-pink">
                                <li>
                                    <a href="#">
                                        <div class="clearfix">
                                            <span class="pull-left">
                                                <i class="btn btn-xs no-hover btn-pink fa fa-comment"></i>
                                                New Comments
                                            </span>
                                            <span class="pull-right badge badge-info">+12</span>
                                        </div>
                                    </a>
                                </li>

                                <li>
                                    <a href="#">
                                        <i class="btn btn-xs btn-primary fa fa-user"></i>
                                        Bob just signed up as an editor ...
                                    </a>
                                </li>

                                <li>
                                    <a href="#">
                                        <div class="clearfix">
                                            <span class="pull-left">
                                                <i class="btn btn-xs no-hover btn-success fa fa-shopping-cart"></i>
                                                New Orders
                                            </span>
                                            <span class="pull-right badge badge-success">+8</span>
                                        </div>
                                    </a>
                                </li>

                                <li>
                                    <a href="#">
                                        <div class="clearfix">
                                            <span class="pull-left">
                                                <i class="btn btn-xs no-hover btn-info fa fa-twitter"></i>
                                                Followers
                                            </span>
                                            <span class="pull-right badge badge-info">+11</span>
                                        </div>
                                    </a>
                                </li>
                            </ul>
                        </li>

                        <li class="dropdown-footer">
                            <a href="#">
                                See all notifications
                                <i class="ace-icon fa fa-arrow-right"></i>
                            </a>
                        </li>
                    </ul>
                </li>-->

                <li class="light-blue dropdown-modal">
                    <a data-toggle="dropdown" href="#" class="dropdown-toggle">
                        <span class="user-info">
                            <small>{% trans "Welcome" %},</small>
                            {{user.username}}
                        </span>

                        <i class="ace-icon fa fa-caret-down"></i>
                    </a>

                    <ul class="user-menu dropdown-menu-right dropdown-menu dropdown-yellow dropdown-caret dropdown-close">

                        <li>
                            <a href="{% url 'account:view' pk=user.id %}">
                            <i class="ace-icon fa fa-user"></i>
                            {% trans "Profile" %}
                            </a>
                        </li>

                        <li class="divider"></li>

                        <li>
                            <a href="{% url 'login:logout' %}">
                            <i class="ace-icon fa fa-power-off"></i>
                            {% trans "Logout" %}
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </div><!-- /.navbar-container -->
</div>

apps/core/templates/core/sidebar.html
{% load i18n %}

<div id="sidebar" class="sidebar                  responsive                    ace-save-state">
    <script type="text/javascript">
        try {
            ace.settings.loadState('sidebar')
        } catch (e) {
        }
    </script>

    <!--<div class="sidebar-shortcuts" id="sidebar-shortcuts">
        <div class="sidebar-shortcuts-large" id="sidebar-shortcuts-large">
            <button class="btn btn-success">
                <i class="ace-icon fa fa-signal"></i>
            </button>

            <button class="btn btn-info">
                <i class="ace-icon fa fa-floppy-o"></i>
            </button>

            <button class="btn btn-warning">
                <i class="ace-icon fa fa-users"></i>
            </button>

            <button class="btn btn-danger">
                <i class="ace-icon fa fa-cog"></i>
            </button>
        </div>

        <div class="sidebar-shortcuts-mini" id="sidebar-shortcuts-mini">
            <span class="btn btn-success"></span>

            <span class="btn btn-info"></span>

            <span class="btn btn-warning"></span>

            <span class="btn btn-danger"></span>
        </div>
    </div><!-- /.sidebar-shortcuts -->

    <ul class="nav nav-list">
        <li class="{{ dashboard_active }}">
            <a href="{% url 'index:index' %}">
            <i class="menu-icon fa fa-tachometer"></i>
            <span class="menu-text"> {% trans "Dashboard" %} </span>
            </a>
            <b class="arrow"></b>
        </li>

        <li class="{{ account_active }}">
            <a href="#" class="dropdown-toggle">
                <i class="menu-icon fa fa-users"></i>
                <span class="menu-text"> {% trans "Users" %} </span>
                <b class="arrow fa fa-angle-down"></b>
            </a>
            <b class="arrow"></b>
            <ul class="submenu">
                <li class="{{ account_viewall_active }}">
                    <a href="{% url 'account:index' %}">
                    <i class="menu-icon fa fa-caret-right"></i>
                    <span class="menu-text"> {% trans "View all" %} </span>
                    </a>
                </li>
                <li class="{{ client_add_active }}">
                    <a href="{% url 'account:add' %}">
                    <i class="menu-icon fa fa-caret-right"></i>
                    <span class="menu-text"> {% trans "Add user" %} </span>
                    </a>
                </li>
            </ul>
        </li>

        <li class="{{ client_active }}">
            <a href="#" class="dropdown-toggle">
                <i class="menu-icon fa fa-building"></i>
                <span class="menu-text"> {% trans "Clients" %} </span>
                <b class="arrow fa fa-angle-down"></b>
            </a>
            <b class="arrow"></b>
            <ul class="submenu">
                <li class="{{ client_viewall_active }}">
                    <a href="{% url 'client:index' %}">
                    <i class="menu-icon fa fa-caret-right"></i>
                    <span class="menu-text"> {% trans "View all" %} </span>
                    </a>
                </li>
                <li class="{{ client_add_active }}">
                    <a href="{% url 'client:add' %}">
                    <i class="menu-icon fa fa-caret-right"></i>
                    <span class="menu-text"> {% trans "Add client" %} </span>
                    </a>
                </li>
            </ul>
        </li>

        <li class="{{ project_active }}">
            <a href="#" class="dropdown-toggle">
                <i class="menu-icon fa fa-industry"></i>
                <span class="menu-text"> {% trans "Projects" %} </span>
                <b class="arrow fa fa-angle-down"></b>
            </a>
            <b class="arrow"></b>
            <ul class="submenu">
                <li class="{{ project_viewall_active }}">
                    <a href="{% url 'project:index' %}">
                    <i class="menu-icon fa fa-caret-right"></i>
                    <span class="menu-text"> {% trans "View all" %} </span>
                    </a>
                </li>
                <li class="{{ project_add_active }}">
                    <a href="{% url 'project:add' %}">
                    <i class="menu-icon fa fa-caret-right"></i>
                    <span class="menu-text"> {% trans "Add project" %} </span>
                    </a>
                </li>
            </ul>
        </li>

        <li class="{{ task_active }}">
            <a href="#" class="dropdown-toggle">
                <i class="menu-icon fa fa-tasks"></i>
                <span class="menu-text"> {% trans "Tasks" %} </span>
                <b class="arrow fa fa-angle-down"></b>
            </a>

            <b class="arrow"></b>
            <ul class="submenu">
                <li class="{{ task_viewall_active }}">
                    <a href="{% url 'task:index' %}">
                    <i class="menu-icon fa fa-caret-right"></i>
                    <span class="menu-text"> {% trans "View all" %} </span>
                    </a>
                </li>
                <li class="{{ task_add_active }}">
                    <a href="{% url 'task:add' %}">
                    <i class="menu-icon fa fa-caret-right"></i>
                    <span class="menu-text"> {% trans "Add task" %} </span>
                    </a>
                </li>
            </ul>
        </li>

        <li class="{{ entry_active }}">
            <a href="#" class="dropdown-toggle">
                <i class="menu-icon fa fa-calendar-check-o"></i>
                <span class="menu-text"> {% trans "Entry" %} </span>
                <b class="arrow fa fa-angle-down"></b>
            </a>

            <b class="arrow"></b>
            <ul class="submenu">
                <li class="{{ entry_viewall_active }}">
                    <a href="{% url 'entry:index' %}">
                    <i class="menu-icon fa fa-caret-right"></i>
                    <span class="menu-text"> {% trans "View all" %} </span>
                    </a>
                </li>
                <li class="{{ entry_add_active }}">
                    <a href="{% url 'entry:add' %}">
                    <i class="menu-icon fa fa-caret-right"></i>
                    <span class="menu-text"> {% trans "Add entry" %} </span>
                    </a>
                </li>
            </ul>
        </li>

        <li class="{{ report_active }}">
            <a href="{% url 'report:index' %}" class="">
                <i class="menu-icon fa fa-file-text-o"></i>
                <span class="menu-text"> {% trans "Reports" %} </span>
            </a>
        </li>


    </ul><!-- /.nav-list -->

    <div class="sidebar-toggle sidebar-collapse" id="sidebar-collapse">
        <i id="sidebar-toggle-icon" class="ace-icon fa fa-angle-double-left ace-save-state"
           data-icon1="ace-icon fa fa-angle-double-left" data-icon2="ace-icon fa fa-angle-double-right"></i>
    </div>
</div>