apps/entry/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.EntryIndexView.as_view(), name='index'),
	url(r'^add/$', views.EntryAddView.as_view(), name='add'),
	url(r'^view/(?P<pk>[0-9]+)/$', views.EntryDetailView.as_view(), name='view'),
	url(r'^edit/(?P<pk>[0-9]+)/$', views.EntryEditView.as_view(), name='edit'),
	url(r'^delete/(?P<pk>[0-9]+)/$', views.EntryDeleteView.as_view(), name='delete'),
	url(r'^(?P<result>.*)$', views.EntryIndexView.as_view(), name='index'),
]

main_site/urls.py
from django.conf.urls import include, url
from django.contrib import admin

handler404 = 'apps.core.views.error404'
handler500 = 'apps.core.views.error500'

urlpatterns = [
	url(r'^admin/', admin.site.urls, name='admin'),
	url(r'^account/', include('apps.account.urls', namespace='account')),
	url(r'^client/', include('apps.client.urls', namespace='client')),
	url(r'^project/', include('apps.project.urls', namespace='project')),
	url(r'^entry/', include('apps.entry.urls', namespace='entry')),
	url(r'^login/', include('apps.login.urls', namespace='login')),
	url(r'^task/', include('apps.task.urls', namespace='task')),
	url(r'^report/', include('apps.report.urls', namespace='report')),
	url(r'^', include('apps.core.urls', namespace='index')),
]

apps/entry/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.timezone import now
from django.utils.translation import ugettext_lazy as _

from apps.client.models import Client
from apps.project.models import Project
from apps.task.models import Task


class Entry(models.Model):
	"""
	Entry table to be used by the Chronos platform.
	TODO: Develop this table
	"""

	description = models.TextField('Description')
	starttime = models.DateTimeField('Start date / time', blank=True, null=True)
	endtime = models.DateTimeField('End date / time', blank=True, null=True)
	duration = models.IntegerField('Duration', blank=True, null=True)
	comments = models.TextField('Comments', blank=True, null=True)
	project = models.ForeignKey(Project, on_delete=models.SET_NULL, db_column='Project', blank=True, null=True)
	client = models.ForeignKey(Client, on_delete=models.SET_NULL, db_column='Client', blank=True, null=True)
	user = models.ForeignKey(User, on_delete=models.SET_NULL, db_column='User', blank=True, null=True)
	task = models.ForeignKey(Task, on_delete=models.SET_NULL, db_column='Task', blank=True, null=True)
	cost = models.DecimalField('Cost', blank=True, null=True, default=0, max_digits=8, decimal_places=2)
	created = models.DateTimeField('Created', default=now, blank=True, null=True)
	last_updated = models.DateTimeField('Last Updated', default=now, blank=True, null=True)

	class Meta:
		# Translators: This string is used to identify the Account table name
		verbose_name = _('Entry')

		# Translators: This string is used to identify the Account table name in plural form
		verbose_name_plural = _('Entries')

apps/entry/forms.py
from django.forms import ModelForm, ModelChoiceField, DateTimeField, DateTimeInput
from django.utils.translation import ugettext_lazy as _

from apps.client.models import Client
from apps.entry.models import Entry
from apps.project.models import Project
from apps.task.models import Task


class FormChoiceField(ModelChoiceField):
    def label_from_instance(self, obj):
        return obj.name


class EntryForm(ModelForm):
    """
    Entry form used to add or update an entry in the Chronos platform.
    TODO: Develop this form
    """

    task = FormChoiceField(
        queryset=Task.objects.all().filter(is_visible=True).order_by('name'),
        empty_label=_('Please select an option'),
        required=False,
    )

    project = FormChoiceField(
        queryset=Project.objects.all().filter(is_visible=True).order_by('name'),
        empty_label=_('Please select an option'),
        required=False,
    )

    client = FormChoiceField(
        queryset=Client.objects.all().filter(is_visible=True).order_by('name'),
        empty_label=_('Please select an option'),
        required=False,
    )

    starttime = DateTimeField(
        input_formats=['%Y-%m-%d %H:%M'],
        widget=DateTimeInput(format='%Y-%m-%d %H:%M')
    )

    endtime = DateTimeField(
        input_formats=['%Y-%m-%d %H:%M'],
        widget=DateTimeInput(format='%Y-%m-%d %H:%M')
    )

    class Meta:
        model = Entry
        fields = ['description', 'starttime', 'endtime', 'comments', 'duration', 'client', 'project', 'task']

apps/entry/views.py
from datetime import datetime
from math import floor
from decimal import Decimal

from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.utils.translation import ugettext_lazy as _
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.contrib.auth.models import User
from django.db.models import Q

from apps.entry.forms import EntryForm
from apps.entry.models import Entry

from apps.client.models import Client
from apps.project.models import Project
from apps.task.models import Task

"""
Entry views created to manage the entry CRUD operation.
"""


class AjaxableResponseMixin(object):
    """
    Mixin to add AJAX support to a form.
    Must be used with an object-based FormView (e.g. CreateView)
    """

    def form_invalid(self, form):
        response = super(AjaxableResponseMixin, self).form_invalid(form)
        if self.request.is_ajax():
            return JsonResponse(form.errors, status=400)
        else:
            return response

    def form_valid(self, form):
        # We make sure to call the parent's form_valid() method because
        # it might do some processing (in the case of CreateView, it will
        # call form.save() for example).
        response = super(AjaxableResponseMixin, self).form_valid(form)
        if self.request.is_ajax():
            data = {
                'result': 'Data saved with success!',
            }
            return JsonResponse(data)
        else:
            return response


class EntryIndexView(LoginRequiredMixin, ListView):
    """
    View that is used to show all the entries that exist in the Chronos platform.
    Receives optional parameters to show alert functions:
    @param result (optional) - Shows alert functions accordingly

        Entry added - YWRkZWQ=
        Entry edited - ZWRpdGVk
        Entry deleted - ZGVsZXRlZA==

    TODO: Develop this view
    """

    template_name = 'entry/entry_index.html'
    model = Entry

    def get_queryset(self):
        return Entry.objects.filter(
            Q(task__is_visible=True) | Q(task__isnull=True),
            Q(project__is_visible=True) | Q(project__isnull=True),
            Q(client__is_visible=True) | Q(client__isnull=True)
        )

    def get_alert_information(self):
        """
        Function used to generate the alert string based on the return result by URL
        :return: String containing the result message
        """
        if 'result' in self.kwargs:
            if self.kwargs['result'] == 'YWRkZWQ=':
                return _("A new entry was added with success!")
            if self.kwargs['result'] == 'ZWRpdGVk':
                return _("The entry information was edited with success!")
            if self.kwargs['result'] == 'ZGVsZXRlZA==':
                return _("The entry information was deleted with success!")

    def get_context_data(self, **kwargs):
        context = super(EntryIndexView, self).get_context_data(**kwargs)
        context['page_title'] = _('Entry list - CHRONOS')
        context['entry_active'] = 'active open'
        context['entry_viewall_active'] = 'active'
        context['result'] = self.get_alert_information()
        context['users'] = User.objects.all()
        context['clients'] = Client.objects.all()
        context['tasks'] = Task.objects.all()
        context['projects'] = Project.objects.all()

        return context


class EntryDetailView(LoginRequiredMixin, DetailView):
    """
    View that is used to show the entry information that exists in the Chronos platform.
    TODO: Develop this view
    """

    template_name = "entry/entry_base.html"
    model = Entry

    def get_context_data(self, **kwargs):
        context = super(EntryDetailView, self).get_context_data(**kwargs)
        context['page_title'] = _('Entry detail - CHRONOS')
        context['entry_active'] = 'active open'
        context['entry_viewall_active'] = 'active'
        context['progress'] = self.get_profile_completion()

        return context

    def get_profile_completion(self):
        """
        This function is used to calculate the total percentage of the entry's profile completion.
        :return: the calculated percentage
        """
        entry = self.get_object()
        filled_fields = 0
        total_fields = len(entry._meta.fields)

        for field in entry._meta.fields:
            if getattr(entry, field.name):
                filled_fields += 1

        progression = floor((filled_fields / total_fields) * 100)

        return progression


class EntryAddView(LoginRequiredMixin, AjaxableResponseMixin,  CreateView):
    """
    View that is used to add a new entry in the Chronos platform.
    TODO: Develop this view
    """

    model = Entry
    form_class = EntryForm
    template_name = 'entry/entry_form.html'

    def get_context_data(self, **kwargs):
        context = super(EntryAddView, self).get_context_data(**kwargs)
        context['page_title'] = _('Add new entry - CHRONOS')
        context['title'] = _('Add a new entry')
        context['entry_active'] = 'active open'
        context['entry_add_active'] = 'active'
        context['is_new_entry'] = True

        return context

    def form_valid(self, form):
        end_time = form.instance.endtime
        start_time = form.instance.starttime

        if end_time > start_time:
            form.instance.duration = (end_time - start_time).seconds / 60
        else:
            form.instance.duration = 0

        form.instance.user = self.request.user

        if form.instance.task:
            if form.instance.duration > 0:
                task_price_min = form.instance.task.price / 60
                form.instance.cost = Decimal.from_float(form.instance.duration) * task_price_min
            else:
                form.instance.cost = 0
        else:
            form.instance.cost = 0

        return super(EntryAddView, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('entry:index', kwargs={'result': 'YWRkZWQ='})


class EntryEditView(LoginRequiredMixin, UpdateView):
    """
    View that is used to edit an entry in the Chronos platform.
    TODO: Develop this view
    """

    model = Entry
    form_class = EntryForm
    template_name = 'entry/entry_form.html'

    def get_context_data(self, **kwargs):
        context = super(EntryEditView, self).get_context_data(**kwargs)
        context['page_title'] = _('Edit entry - CHRONOS')
        context['title'] = _('Edit entry')
        context['entry_active'] = 'active open'
        context['entry_viewall_active'] = 'active'
        context['is_new_entry'] = False

        return context

    def form_valid(self, form):
        end_time = form.instance.endtime
        start_time = form.instance.starttime

        if end_time > start_time:
            form.instance.duration = (end_time - start_time).seconds / 60
        else:
            form.instance.duration = 0

        form.instance.last_updated = datetime.now()

        if form.instance.task:
            if form.instance.duration > 0:
                task_price_min = form.instance.task.price / 60
                form.instance.cost = Decimal.from_float(form.instance.duration) * task_price_min
            else:
                form.instance.cost = 0
        else:
            form.instance.cost = 0

        return super(EntryEditView, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('entry:index', kwargs={'result': 'ZWRpdGVk'})


class EntryDeleteView(LoginRequiredMixin, DeleteView):
    """
    View that is used to delete an entry in the Chronos platform. Accessed via AJAX call
    TODO: Develop this view
    """
    model = Entry
    template_name = 'entry/entry_delete_modal.html'

    def dispatch(self, *args, **kwargs):

        id = self.get_object().id

        response = super(EntryDeleteView, self).dispatch(*args, **kwargs)
        if self.request.is_ajax():
            response_data = {"result": "ok", "id": id}
            return JsonResponse(response_data)
        else:
            # POST request (not ajax) will do a redirect to success_url
            return response

    def get_success_url(self):
        return reverse_lazy('entry:index', kwargs={'result': 'ZGVsZXRlZA=='})

apps/entry/templates/entry/client_delete_modal.html
{% load i18n %}
<div class="modal-dialog">
    <div class="modal-content">
        <form action="" method='POST'>
            {% csrf_token %}
            <div class="modal-header">
                <h4 class="modal-title">{% trans "Delete entry" %}</h4>
            </div>
            <div class="modal-body">
                <p>
                    {% trans "Are you sure you would like to delete this entry? You will not be able to undo this operation!" %}
                </p>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary">{% trans "Delete" %}</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">{% trans "Cancel" %}</button>
            </div>
        </form>
    </div
</div>

apps/entry/templates/entry/entry_index.html
{% extends "core/base.html" %}
{% load i18n l10n widget_tweaks %}

{% block content %}
<div class="breadcrumbs ace-save-state" id="breadcrumbs">
    <ul class="breadcrumb">
        <li>
            <i class="ace-icon fa fa-home home-icon"></i>
            <a href="{% url 'index:index' %}">{% trans "Home" %}</a>
        </li>
        <li class="active">{% trans "Entries" %}</li>
    </ul><!-- /.breadcrumb -->
</div>
<div class="page-content">
    <div class="page-header">
        <h1>
            {% trans "Entry list" %}
        </h1>
    </div><!-- /.page-header -->
    {% if result %}
    <div class="row">
        <div class="col-xs-12">
            <div class="alert alert-success">
                <button type="button" class="close" data-dismiss="alert">
                    <i class="ace-icon fa fa-times"></i>
                </button>
                <i class="ace-icon fa fa-check"></i> {{ result }}
                <br>
            </div>
        </div>
    </div>
    {% endif %}
    <div class="row">
        <div class="col-xs-12">
            <!-- PAGE CONTENT BEGINS -->
            <div class="row">
                <div class="col-xs-12">
                    <div class="clearfix">
                        <div class="widget-box collapsed widget-color-blue">
                            <div class="widget-header widget-header-small">
                                <h4 class="widget-title"><i class="ace-icon fa fa-sliders light-green bigger-130"></i>&nbsp;{% trans "Refine your search" %}</h4>
                                <div class="widget-toolbar" id="search-widget-toolbar">
                                    <a href="#" data-action="collapse">
                                        <i class="ace-icon fa fa-chevron-down"></i>
                                    </a>
                                </div>
                            </div>
                            <div class="widget-body" id="search-widget-body">
                                <div class="widget-main no-padding">
                                    <form>
                                        <fieldset>
                                            <div class="form-group">
                                                <div class="row">
                                                    <div class="col-xs-4">
                                                        <h4 class="blue smaller">
                                                            <i class="fa fa-calendar orange bigger-110"></i>&nbsp;{% trans "Calendar" %}
                                                        </h4>
                                                        <div class="row">
                                                            <div class="col-xs-12">
                                                                <div class="input-daterange input-group">
                                                                    <input type="text" class="form-control" id="start_date" name="start">
                                                                    <span class="input-group-addon">
                                                                        <i class="fa fa-exchange"></i>
                                                                    </span>
                                                                    <input type="text" class="form-control" id="end_date" name="end">
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="col-xs-4">
                                                        <h4 class="blue smaller">
                                                            <i class="fa fa-pencil-square-o red bigger-110"></i>&nbsp;{% trans "Basic details" %}
                                                        </h4>
                                                        <div class="row">
                                                            <div class="col-xs-6">
                                                                <select class="chosen-select form-control" id="id_task" name="task">
                                                                    <option value="" selected="selected">{% trans "Please select a task" %}</option>
                                                                    {% for task in tasks %}
                                                                    <option value="{{task.name}}">{{task.name}}</option>
                                                                    {% endfor %}
                                                                </select>
                                                            </div>
                                                            <div class="col-xs-6">
                                                               <select class="chosen-select form-control" id="id_user" name="user">
                                                                    <option value="" selected="selected">{% trans "Please select a user" %}</option>
                                                                    {% for user in users %}
                                                                    <option value="{{user.username}}">{{user.username}}</option>
                                                                    {% endfor %}
                                                                </select>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="col-xs-4">
                                                        <h4 class="blue smaller">
                                                            <i class="fa fa-industry purple bigger-110"></i>&nbsp;{% trans "Project details" %}
                                                        </h4>
                                                        <div class="row">
                                                            <div class="col-xs-6">
                                                                <select class="chosen-select col-xs-10 col-sm-5" id="id_client" name="client">
                                                                    <option value="" selected="selected">{% trans "Please select a client" %}</option>
                                                                    {% for client in clients %}
                                                                    <option value="{{client.name}}">{{client.name}}</option>
                                                                    {% endfor %}
                                                                </select>
                                                            </div>
                                                            <div class="col-xs-6">
                                                                <select class="chosen-select form-control" id="id_project" name="project">
                                                                    <option value="" selected="selected">{% trans "Please select a project" %}</option>
                                                                    {% for project in projects %}
                                                                    <option value="{{project.name}}">{{project.name}}</option>
                                                                    {% endfor %}
                                                                </select>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </fieldset>
                                    </form>
                                    <div class="form-actions left no-margin">
                                         <button id="search_update" type="button" class="btn btn-default btn-round btn-white">
                                            <i class="ace-icon fa fa-search green"></i>
                                            {% trans "Search" %}
                                        </button>
                                        <button id="search_reset" type="button" class="btn btn-default btn-round btn-white">
                                            <i class="ace-icon fa fa-remove red2"></i>
                                            {% trans "Reset" %}
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="space-10"></div>
            <div class="row">
                <div class="col-xs-12">
                    <div class="clearfix">
                        <div class="pull-right tableTools-container"></div>
                    </div>
                    <div class="table-header">
                        {% trans "Results for Entry listing" %}
                    </div>

                    <!-- div.table-responsive -->

                    <!-- div.dataTables_borderWrap -->
                    <div>
                        <table id="entry-table" class="table table-striped table-bordered table-hover">
                            <thead>
                            <tr>
                                <th class="center">
                                    <label class="pos-rel">
                                        <input type="checkbox" class="ace"/>
                                        <span class="lbl"></span>
                                    </label>
                                </th>
                                <th>{% trans "ID" %}</th>
                                <th>{% trans "Task" %}</th>
                                <th>{% trans "Description" %}</th>
                                <th class="hidden-480">{% trans "Start time" %}</th>
                                <th class="hidden-480">{% trans "End time" %}</th>
                                <th>{% trans "Duration (min.)" %}</th>
                                <th>{% trans "Cost (EUR)" %}</th>
                                <th>{% trans "User" %}</th>
                                <th>{% trans "Client" %}</th>
                                <th>{% trans "Project" %}</th>
                                <th class="hidden-480">{% trans "Comments" %}</th>
                                <th></th>
                            </tr>
                            </thead>

                            <tbody id="entry-table-body">

                            {% for entry in object_list %}
                            <tr id="pk-{{entry.id}}">
                                <td class="center">
                                    <label class="pos-rel">
                                        <input type="checkbox" class="ace"/>
                                        <span class="lbl"></span>
                                    </label>
                                </td>

                                <td><a href="#">{{entry.id}}</a></td>
                                <td>{{entry.task.name}}</td>
                                <td>{{entry.description}}</td>
                                <td class="hidden-480">{{entry.starttime | date:'Y-m-d H:i'}}</td>
                                <td class="hidden-480">{{entry.endtime | date:'Y-m-d H:i'}}</td>
                                <td>{{entry.duration}}</td>
                                <td>{{entry.cost}}</td>
                                <td>{{entry.user.username}}</td>
                                <td>{{entry.client.name}}</td>
                                <td>{{entry.project.name}}</td>
                                <td class="hidden-480">{{entry.comments}}</td>
                                <td>
                                    <div class="hidden-sm hidden-xs action-buttons">
                                        <a class="blue" href="{% url 'entry:view' pk=entry.id %}">
                                            <i class="ace-icon fa fa-eye bigger-130"></i>
                                        </a>

                                        <a class="green" href="{% url 'entry:edit' pk=entry.id %}">
                                            <i class="ace-icon fa fa-pencil bigger-130"></i>
                                        </a>

                                        <a class="delete red" href="{% url 'entry:delete' pk=entry.id %}"
                                           title="Delete entry information" data-tooltip>
                                            <i class="ace-icon fa fa-trash-o bigger-130"></i>
                                        </a>
                                    </div>
                                </td>
                            </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <!-- PAGE CONTENT ENDS -->
        </div><!-- /.col -->
    </div><!-- /.row -->
</div><!-- /.page-content -->
{% endblock %}

{% block bottom %}
{% include "entry/entry_index_bottom_js.html" %}
{% endblock %}